language: python
python:
  - "2.7"

install:
  - pip install -e git+https://github.com/tonioo/modoboa.git#egg=modoboa
  - python setup.py -q develop
  - pip install -q psycopg2

before_script:
  - psql -c 'create database modoboa_test;' -U postgres

script: 
  - python -m unittest tests
