language: python
python:
  - "2.7"

env:
  - DJANGO=1.7

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -e git+https://github.com/tonioo/modoboa.git@split_applications#egg=modoboa
  - python setup.py -q install
  - pip install -q psycopg2 --use-mirrors

before_script:
  - mysql -e 'create database modoboa_test;'
  - psql -c 'create database modoboa_test;' -U postgres

script: 
  - python -m unittest tests
