language: python
python:
  - "2.7"

env:
  - DJANGO=1.7

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
  - pip install -q MySQL-python --use-mirrors

before_script:
  - mysql -e 'create database modoboa_test;'
  - psql -c 'create database modoboa_test;' -U postgres

script: 
  - python -m unittest tests
